name: sandys_snacks_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Firebase - Fixed combination

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # # Force compatible versions - fix the Firestore aggregate issue
  # dependency_overrides:
  #   # Core Firebase packages
  #   firebase_core: 2.24.2
  #   firebase_auth: 4.15.3
  #   cloud_firestore: 4.13.6

  # Internal packages
  _flutterfire_internals: ^1.3.60

  # Web implementations - use older Firestore web
  firebase_core_web: ^3.0.0
  firebase_auth_web: ^6.0.0
  cloud_firestore_web: ^5.0.0 # Older version without sum parameter issue

  # Platform interfaces - match the Firestore web version
  firebase_core_platform_interface: ^6.0.0
  firebase_auth_platform_interface: ^8.0.0
  cloud_firestore_platform_interface: ^7.0.0 # Compatible with 3.8.6

  # Supporting packages
  js: ^0.7.2

flutter:
  uses-material-design: true
